### ISSUE TITLE
output messaging counts stopped apps which may confuse people

### ISSUE THREAD

**Issue by jbayer** [krujos/usagereport-plugin#1]
"is using" is the language used when reporting the org memory usage, but that _does not_ count stopped applications.

"is using" is the language used when reporting the space memory usage, but that _does_ count stopped applications.

perhaps consider more detail such as "actively using" and some other category like "is allocated but not running". the challenge will be when a space has a mix of both, but it's probably better to report both concepts with clear description rather than change the definition of "is using" based on the context.

similar issue at the bottom of the output: `You are running 12 apps in all orgs, with a total of 15 instances.` but in this case i am not actively running any applications in either of these 2 orgs. breaking it down to both running apps and apps that are stopped would be more clear.

```
$ cf usage-report
Gathering usage information
Org jbayer-normal-org is using 0 MB of 10240 MB.
    Space development is using 4864 MB memory (47%) of org quota. 8 apps 11 instances.
    Space staging is using 1280 MB memory (12%) of org quota. 2 apps 2 instances.
    Space production is using 0 MB memory (0%) of org quota. 0 apps 0 instances.
Org jbayer-zeroquota-org is using 0 MB of 2048 MB.
    Space development is using 1280 MB memory (62%) of org quota. 2 apps 2 instances.
    Space staging is using 0 MB memory (0%) of org quota. 0 apps 0 instances.
    Space production is using 0 MB memory (0%) of org quota. 0 apps 0 instances.
You are running 12 apps in all orgs, with a total of 15 instances.
```

**Comment by krujos** [comment]
Thanks @jbayer! Appreciate you trying it out.

I think not "charging" for stopped apps is the right thing. 

Would something like this clear it up? A little busy, but I think it contains the information you're after?

```
Org jbayer-normal-org is consuming 0 MB of 10240 MB.
    Space development is consuming 0 MB memory (0% of org quota).
         8 apps: 0 running 8 stopped
         11 instances: 0 running 11 stopped
Org jbayer-zeroquota-org is using 0 MB of 2048 MB.
    Space development is using 1280 MB memory (62%) of org quota. 2 apps 2 instances.
         2 apps: 2 running, 0 stopped
         2 instances: 2 running, 0 stopped
    Space staging is using 0 MB memory (0%) of org quota. 0 apps 0 instances.
         0 apps: 0 running, 0 stopped
         0 instances: 0 running, 0 stopped
    Space production is using 0 MB memory (0%) of org quota. 0 apps 0 instances.
         0 apps: 0 running, 0 stopped
         0 instances: 0 running, 0 stopped
Your install has 12 apps in all orgs, with a total of 15 instances.
   1 of your apps is running (11 stopped)
   2 of your instances are running (13 stopped)
```

**Comment by jbayer** [comment]
yes, i think that does a nice job of clearing up the ambiguity.

at some point you could also solicit advice from @pivotal-plech and the rest of the design team if you'd like.
