### ISSUE TITLE
Unable to install, plugin is not available from the given url.

### ISSUE THREAD

**Issue by chetan-hireholi** [krujos/usagereport-plugin#13]
$ cf install-plugin 'Usage Report' -r CF-Community

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

Do you want to install the plugin Usage Report? (y or n)> y
Looking up 'Usage Report' from repository 'CF-Community'
FAILED
Download attempt failed: open C:\cygwin64\tmp\true: is a directory

Unable to install, plugin is not available from the given url.

**Comment by chetan-hireholi** [comment]
Can anyone please let me know any updates on this issue?

**Comment by krujos** [comment]
Are you on win64? I've never tried it with cygwin, can you try from a normal shell?

**Comment by chetan-hireholi** [comment]
Hello,

I managed to download the binaries from GitHub and installed it offline. It
works like a charm. Thank you for the reply.


*Regards, *
*Chetan Hireholi*
