### ISSUE TITLE
CLI 6.18 & 6.19 fail to install plugin on 64 bit Windows 7

### ISSUE THREAD

**Issue by jhliptak** [krujos/usagereport-plugin#8]
Install fails with
PS G:> cf install-plugin 'Usage Report' -r CF-Community

**Attention: Plugins are binaries written by potentially untrusted authors. Install and use plugins at your own risk.**

Do you want to install the plugin Usage Report? (y or n)> y
Looking up 'Usage Report' from repository 'CF-Community'
FAILED
Plugin requested has no binary available for your OS: windows, 386

**Comment by krujos** [comment]
I don't have a way to test this, mind checking that the attached [usagereport-plugin.exe.zip](https://github.com/krujos/usagereport-plugin/files/315125/usagereport-plugin.exe.zip) (sha1 on the executable is 0bf9769eb0ba7039a73b31e506d63f5f1663c4e2) suits your needs and I'll make the required changes to the build scripts. 

Should you not want a random executable build it from source with: 

```
 $  go get
 $  GOOS=windows GOARCH=386 go build
```

**Comment by jhliptak** [comment]
Works great!

John Liptak
Principal Architect
Infrastructure Architecture & Strategy
931 14th St
Denver, CO 80202
John.Liptak@CenturyLink.commailto:John.Liptak@CenturyLink.com
(303) 992-9623 (work)
(303) 437-4206 (cell)

All problems in computer science can be solved by another level of indirection" – Butler Lampson
